stages:
  - build

build_image:
  stage: build
  image: docker:latest
  variables:
    IMAGE_VERSION: $CI_COMMIT_TAG
    IMAGE_HASH: $CI_COMMIT_SHORT_SHA
  services:
    - docker:dind
  before_script:
    - apk add make
    - docker login -u $DOCKER_HUB_REGISTRY_USER -p $DOCKER_HUB_REGISTRY_TOKEN
    - docker login -u $HARBOR_USERNAME -p $HARBOR_PASSWORD $HARBOR_HOST
  script:
    - make build_push
  only:
    - tags
  except:
    - branches
