name: Docker image flow
run-name: ${{ github.actor }} is learning GitHub Actions
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: make build_load_local
